require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  TargetRailsVersion: 7.0
  Exclude:
    - bin/**
    - vendor/**/*
    - db/schema.rb
    - tmp/**/*
    - public/**/*

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Max: 50

Rails/BulkChangeTable:
  Enabled: false
