version: '3.7'

services:
  db:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --local-infile=1 --collation-server=utf8mb4_general_ci
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: 'Asia/Tokyo'

volumes:
  db: